feat: useIgnorePointer added and widget made a clickable
AppNation/before_after pull request #2
Opened 2024-09-18 13:17 UTC by erenincesu1010

2024-09-18 13:20 UTC, emircetn requested changes

2024-09-18 13:20 UTC, emircetn commented on lib/src/before_after.dart
> +    this.useIgnorePointer = false,
ismi biraz daha spesifik verebilir misin? @erenincesu1010

2024-09-18 13:44 UTC, erenincesu1010 commented on lib/src/before_after.dart
> +    this.useIgnorePointer = false,
84366ad4bc0d16067c1783d4c792af426d99621e

2024-09-18 13:44 UTC, erenincesu1010 commented on lib/src/before_after.dart
> +    this.useIgnorePointer = false,
@emircetn düzeltildi

2024-09-18 13:49 UTC, emircetn approved these changes

2024-09-19 08:06 UTC, cankarabag commented on lib/src/before_after.dart
> +                        child: CustomPaint(
CustomPaint'i IgnorePointer ile sarmaladıktan sonra widget.disableTouchInteraction şartını ignoring parametresine vermek daha temiz olabilir

2024-09-19 08:13 UTC, erenincesu1010 commented on lib/src/before_after.dart
> +                        child: CustomPaint(
d456adf93af202001950bf5f503b1b717cc06f29

2024-09-19 08:13 UTC, erenincesu1010 commented on lib/src/before_after.dart
> +                        child: CustomPaint(
güncellendi

2024-09-19 08:22 UTC, merged